name: Bug report
description: Report a reproducible defect in FairCareAI
title: "[Bug]: "
labels:
  - bug
  - triage
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting this. Please include a minimal reproducible example and expected vs actual behavior.
  - type: input
    id: summary
    attributes:
      label: Summary
      description: One-sentence description of the bug.
      placeholder: Calibration plot labels overlap for subgroup-heavy reports.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Reproduction steps
      description: Exact commands/code to reproduce.
      placeholder: |
        1. Run faircareai audit ...
        2. Export governance HTML ...
        3. Open report and observe ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Paste Python/platform/package versions.
      placeholder: |
        OS: macOS 14
        Python: 3.12.3
        faircareai: 0.2.0
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs or traceback
      render: shell
